apiVersion: v1
kind: Pod
metadata:
  name: k8-pod
  labels:
    app: web
spec:
  containers:
    - name: democontainer
      image: sample-api
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8-service
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
